### ISSUE TITLE
Image in readme is not readable in dark theme

### ISSUE THREAD

**Issue by avila** [haghish/rcall#13]
Very small issue: github now supports dark themes and the image in the Readme file is not well readable due to transparency and dark text. 

![image](https://user-images.githubusercontent.com/31955632/113011095-b6455700-9179-11eb-8361-741f577dc586.png)

**Comment by avila** [comment]
The example images are fine. 
![image](https://user-images.githubusercontent.com/31955632/113011497-2653dd00-917a-11eb-95f8-b571cf96d53c.png)

**Comment by haghish** [comment]
thanks. it will be fixed in the next update
