### ISSUE TITLE
Is it possible to have rcall print warnings within R to the Stata screen automatically? 

### ISSUE THREAD

**Issue by jonathandroth** [haghish/rcall#14]
This would be a useful feature for wrappers for R packages implementing rcall. Thanks!

**Comment by haghish** [comment]
this is not an issue but rather a feature request. I am not sure if I have the time to implement it now, but you're more than welcome to implement it and add an option for reporting warnings. Basically, if you catch your warnings as string objects, rcall will return them automatically! 

If you do so, I recommend defining a object in R named `warnings` and storing the warnings in it. Then `rcall` will return it as a macro automatically.

**Comment by haghish** [comment]
rcall BETA3.0.2 returns warnings automatically. it is in developmental version so testing the new feature would be a favor. Thanks for the suggestion
