### ISSUE TITLE
call_return.ado chokes on large numeric matrix

### ISSUE THREAD

**Issue by heelguru** [haghish/rcall#15]
I have a call that is due to return a large (>500 entries) numeric matrix on the stable version. This fails for two reasons:
1. A valid R Matrix may contain NA as a value <- call_return doesn't handle this at the moment and Stata doesn't like mixtures of text and numbers in Stata's default matrix language.

My hacky solution to this issue is to define a new local at line 198 of call_return as follows:

`local content2:subinstr local content "NA" ".",all`

This requires the incremental loop to squeeze in the return from R in terms of content 3.

2. The logic to `// AVOID STATA LIMITS IN TERMS OF NUMBER OF ARGUMENTS`
is broken
in part of the subloops in there you have a statement to check if a matrix is missing:

`// append pieces of the long returned matrix
						if missing("`name'") {`

yet this is checking for the existence of the macro literal string, rather than the existence of a matrix. So the loop always continues to the second loop. The issue then is that the matrix may or may not exist, which then needs to be fixed by using `nullmat()`

like so:

							`matrix `name' = nullmat(`name') , `content3'`

The final issue is that the code crashes with the above fix as the loop assumes the maximum numeric literals that stata can handle at any given point is 500. This is not true, it can only handle 300.

Thus the refactored code to avoid stata limits is:

`				// AVOID STATA LIMITS IN TERMS OF NUMBER OF ARGUMENTS	
				// ------------------------------------------------------------
				if wordcount(`"`macval(content)'"') <= 300  {
					matrix define `name' = (`content')
				}
				else {
					local content2:subinstr local content "NA" ".",all
					local content3:subinstr local content2 "," "",all
					tokenize "`content3'"
					while !missing("`1'") {
						local n 0      //RESET
						local content4 //RESET
						
						// append pieces of the long returned matrix
							matrix `name' = nullmat(`name'), `1'
						macro shift
					}
				}		`

I note the beta has already adopted a more efficient approach, but for the moment this has a bug (please see next bug report)

**Comment by haghish** [comment]
thank you for this. I will get back to it after changing the matrix handling mechanism in the version 3.0

**Comment by haghish** [comment]
I think the BETA version I updated should solve this bug. The new version can handle very large matrices! If the new update doesn't solve the problem, let me know and I re-open the issue.
