### ISSUE TITLE
call_return.ado bug

### ISSUE THREAD

**Issue by heelguru** [haghish/rcall#16]
There seems to be an issue in the beta of call_return.ado when returning a matrix.

The code tries to label the matrix names by creating a local called `variablelist` but this is incremented in a loop, but the macro predates it and contains `c1' which is why there is an error:

`variable c1 not found
r(111);`

To solve the issue, the local `variablelist` needs to be reset in line 198 of call_return.ado (yes, I know this should probably be a pull request)

**Comment by haghish** [comment]
thanks for this. indeed, try a pull request. it's your credite mate :) 

in case you're wondering, the 3.0 BETA is about handing the matrices. Stata has a limit for macro length and storing large vectors or matrices as macros is limited in length. The new procedure stores the matrices as data sets and communicates them between R and Stata. So basically, the bugs you've reported are valid and need to be addressed. I will appreciate the pull request! 

Cheers

**Comment by heelguru** [comment]
Pull request made.

I do have a separate, if related issue. There may be instances where the matrix returned by R is full of NA missing files. I think the new code replaces these with Stata missings. But there may be instances (like when trying to estpost a matrix) where zeros may be desired instead. Think this could be an option somehow?

**Comment by haghish** [comment]
actually, do you have an example to reproduce the error that can be solved by resetting the `variablelist`? 

I don't seem to get the first pullrequest

**Comment by haghish** [comment]
also, try to reinstall the BETA version, which just got updated
