### ISSUE TITLE
"Sticky" errors

### ISSUE THREAD

**Issue by NickCH-K** [haghish/rcall#19]
A common problem I have when working with rcall is that sometimes (but only sometimes) if I get an error, then that error will be "sticky" and every subsequent `rcall` command I give returns the same error, even if there is no error in the code that I've sent. `rcall, clear` sometimes resolves the issue but not always.

This can make debugging anything a big pain as I'm constantly having to close and reopen Stata to clear the bug. Is there any way around this?

Sorry for the long reproducible example, as this appears to pop up sporadically. After installing [did](https://github.com/NickCH-K/did) and running `didsetup`:

```{stata}
mpdta, clear
att_gt lemp year firsttreat lpop, idname(countyreal)

local type = "group"
local opt_balance_e = "NULL"
local opt_min_e = "-Inf"
local opt_max_e = "Inf"
local narm_TF = "FALSE"
local boot_TF = "NULL"
local opt_biters = "NULL"
local cband_TF = "NULL"
local opt_alpha = "NULL"
local clusters = "NULL"

* Run interactively so other functions can use
* the model output
* "dotter" turns R NA's into Stata NA's
noisily rcall: library(did); ///
dotter <- function(M) {; ///
	if (sum(is.na(M)) > 0) M[is.na(M)] <- '.'; ///
	return(M) ; ///
}; ///
err <- try(TE <- aggte(CS_Model, ///
					type = '`type'', ///
					balance_e = `opt_balance_e', ///
					min_e = `opt_min_e', ///
					max_e = `opt_max_e', ///
					na.rm = `narm_TF', ///
					bstrap = `boot_TF', ///
					biters = `opt_biters', ///
					cband = `cband_TF', ///
					alp = `opt_alpha', ///
					clustervars = `clusters')); ///
if (inherits(err, 'try-error')) { ///
	error <- err[1]; ///
} else { ///
	overall_effect <- TE[['overall.att']]; ///
	overall_se <- TE[['overall.se']]; ///
	overall_crit_value <- qnorm(1-TE[['DIDparams']][['alp']]/2); ///
	overall_cband_upper <- TE[['overall.att']] + overall_crit_value*TE[['overall.se']]; ///
	overall_cband_lower <- TE[['overall.att']] - overall_crit_value*TE[['overall.se']]; ///
	table <- cbind.data.frame(TE[['overall.att']], TE[['overall.se']], overall_cband_lower, overall_cband_upper); ///
	if (TE[['type']] != 'simple') {; ///
		cband_lower <- TE[['att.egt']] - TE[['crit.val.egt']]*TE[['se.egt']]; ///
		cband_upper <- TE[['att.egt']] + TE[['crit.val.egt']]*TE[['se.egt']]; ///
		table[2:(length(TE[['egt']])+1),] <- cbind.data.frame(TE[['att.egt']], TE[['se.egt']], cband_lower, cband_upper); ///
	}; ///
	cband_text1a <- paste0(100*(1-TE[['DIDparams']][['alp']]),"%"); ///
	colnames(table) <- c("ATT","SE", ///
							paste0('CI',cband_text1a,'_Bot'),  ///
							paste0('CI',cband_text1a,'_Top')); ///
	rownames(table) <- c('Overall', TE[['egt']]); ///
	table <- dotter(as.matrix(table)); ///
	rm(overall_cband_lower, overall_cband_upper, cband_upper, cband_lower, cband_text1a); ///
}
****** RETURNS ERROR:
* factor-variable and time-series operators not allowed

rcall: a <- 1
****** RETURNS ERROR:
* factor-variable and time-series operators not allowed

. rcall, clear
****** RETURNS ERROR:
* factor-variable and time-series operators not allowed

. rcall: a <- 1
****** RETURNS ERROR:
* factor-variable and time-series operators not allowed
```

**Comment by haghish** [comment]
I couldn't get to install "did" R package to examine your code on my current machine. I can make two quick comments here and then will investigate the issue in more details later.

1. `rcall, clear` is a wrong syntax for clearing the rcall environment. Use `rcall clear` without the comma. `clear` is a command not an option
2. A _sticky_ error - in interactive mode - could be caused by rcall, trying to pass something to Stata. Since the variable is defined in the global environment of R, after executing each command, rcall tries to return it to Stata. But I can't say more at this point before figuring out where does __* factor-variable and time-series operators not allowed__ error come from... Perhaps you could hlp with that?

**Comment by NickCH-K** [comment]
1. Oops! I recall making (and fixing) the same mistake in the past and finding that `rcall clear` didn't fix it either, but I'll check again when another sticky error pops up
2. This would make sense, if the same difficult-to-pass object remains in the R environment. Unfortunately I have no idea where the factor-variable error (which is clearly a Stata error rather than an R error) is coming from. I suspect one of the `.`s in the code but I've yet to be able to track it down yet.

**Comment by haghish** [comment]
That's very strange. `rcall clear` should solve it. Do you get the message that `(R memory cleared)`? `rcall clear` does not enter R environment at all, so no error should be returned after this command, apart from `(R memory cleared)`... 

Anyway, if we could find a class of variable that `rcall` thinks it can return to Stata but fails to do so, I can fix it.

**Comment by NickCH-K** [comment]
I reran the code from my original post and got a *different* sticky error this time of "too few quotes". `rcall clear` fixed it though (phew!) so maybe my memory was wrong (or that was a problem with an older version of **rcall**)

**Comment by haghish** [comment]
1. this is my favorite Stata error! You've got to debug it in small chunks. You pass a code that includes quotation mark which interferes with rcall... 
2. This error could happen at any stage, even before calling R, depending on your code... 
3. glad that `rcall clear` worked!
