### ISSUE TITLE
Simple st.var() example from rcall help file not working

### ISSUE THREAD

**Issue by bbachilles** [haghish/rcall#20]
Thanks for all your work on a great tool for Stata users to access R. When I try to run the following commands, from the rcall help file, I get an error message from the `lm` call. I'm using Stata 16 and R 4.0.3.

```
sysuse auto, clear
rcall: dep <- st.var(price)
rcall: pre <- st.var(mpg)
rcall: lm(dep~pre)
```
```
Warning message:
 In  :  
Error in model.frame.default(formula = dep ~ pre, drop.unused.levels = TRUE) :  invalid type (list) for variable 'dep'
```

Both variables are stored as data.frame objects. However, something about the way they are stored makes them inaccessible to lm or other functions, e.g., `rcall: mean(pre)` gives a similarly-flavored error message: 

`In mean.default(dep) : argument is not numeric or logical: returning NA `.

Interestingly, I can coerce them to be useful by loading `dplyr`:

`rcall: library(dplyr); pre %>% summarize(mpg)`

```
  mean(mpg)
1   21.2973

```

Any help would be most appreciated!

**Comment by haghish** [comment]
That was a bug introduced by version 3.0! Thank you so much for noticing it. it's fixed now. Try version 3.0.5
