### ISSUE TITLE
`vanilla` option dropped when using `rcall script`

### ISSUE THREAD

**Issue by bquistorff** [haghish/rcall#25]
When calling `rcall script` the `vanilla` option is dropped. See the lower line
https://github.com/haghish/rcall/blob/1d25969ff7bf91beb633ee27ef95ff67caa23688/rcallscript.ado#L13-L14

I tried changing the lower line locally to :
```
rcall `vanilla': `args' source("`macval(using)'")
```
and that works for me, but I'm not sure what other implications this might have. (Seems like the upper line wasn't used for a reason.)

**Comment by haghish** [comment]
I think I solved that problem. Somewhere I had forgotten to add the vanilla macro. Also, with `script`, vanilla would be an option and not a subcommand. I check that again

**Comment by haghish** [comment]
see how I had fixed it: https://github.com/haghish/rcall/blob/master/rcallscript.ado
