### ISSUE TITLE
Version 1.0.2 - error in file(file, ifelse(append, "a", "w"))

### ISSUE THREAD

**Issue by Chris-M-P** [haghish/rcall#3]
Excellent idea to keep packages loaded (I was going to request this!) - it seems to have broken things on Win7 though.

Error message:
error in file(file, ifelse(append, "a", "w")):
cannot open the connection

Warnings:
1. In file.create(stata.output) : 
cannot create file 'C:/WIndows/stata.output', reason 'Permission denied'
2. In file(file.ifelse(append, "a", "w")) : 
cannot open file 'C:/Windows/stata.output': Permission denied

**Comment by haghish** [comment]
Dammit. It worked fine on Windows 10 when I tested it yesterday. What is it with the `Permission denied` warning you get? 

when do you get this error? with any R command?

**Comment by Chris-M-P** [comment]
Aha - these errors were due to the restrictions on my Uni computer. Running Stata with elevated user rights has solved these problems - it works fine now. This might limit its usability for some people - I'm guessing you've got full admin rights on your Win10 machine? If so, I'd be happy to test any changes in a more locked down environment if helpful?

**Comment by haghish** [comment]
@Chris-M-P I had the same problem with [MarkDoc](http://www.haghish.com/statistics/stata-blog/reproducible-research/markdoc.php) package for writing files. It's just a Windows issue that the user should have the privilege to create files in specific directories. You cannot change the directory permissions (to write and erase files) if you are a restricted user, the way I understand Windows (I'm a Mac & Linux guy).

**Comment by haghish** [comment]
@Chris-M-P It's VERY KIND of you to offer that. Please do. If you're following my GitHub account you'll see the changes. I assume you can also "watch" the package and get the same feed? Anyway, I warmly welcome any cooperation.
