### ISSUE TITLE
macro to R

### ISSUE THREAD

**Issue by yanyu2015** [haghish/rcall#35]
This is an excellent package; however, I encounter some issues.
I would like to inquire whether rcall supports retrieving a global macro with multiple variables from Stata.
For example:
```
global a "x1 x2"
rcall: (ar <- $a)
```
Unfortunately, this code does not execute successfully.

**Comment by haghish** [comment]
Hi. Please read the paper that introduces the syntax: https://journals.sagepub.com/doi/pdf/10.1177/1536867X19830891 

**Answer:**

    global a "x1 x2"
    rcall: (ar <- "$a")
