### ISSUE TITLE
Installation without internet access

### ISSUE THREAD

**Issue by FelixStips** [haghish/rcall#38]
I am using Stata in a remote desktop without internet access. I can either copy ados into my personal folder or use specific net install commands from the boston repository. I understand that neither of these procedures will be possible for Rcall, correct? Do you perhaps have other ideas to install the packages?

**Comment by haghish** [comment]
You can download the rcall and its dependency R packages (https://github.com/haghish/rcall/blob/master/dependency.do) and install them offline as usual Stata & R packages. Please post your future questions on statalist.org.
