### ISSUE TITLE
Rcall fails to load data frame if file name has parentheses

### ISSUE THREAD

**Issue by aalexandersson** [haghish/rcall#4]
For example, this works on my PC:
R: mydata <- st.data(C:\Users\krolm\Documents/auto.dta)

But this fails
R: mydata <- st.data(C:\Program Files (x86)\Stata14\ado\base\a\auto.dta)

with error
file C:\Program Files (x86 not found
r(601);

Would double compund quotes in Rcall solve the issue?
. confirm file `"`filename'"'

**Comment by haghish** [comment]
it should be fixed now (reinstall). Please confirm by closing the issue!

**Comment by aalexandersson** [comment]
Fixed. Thanks!

**Comment by aalexandersson** [comment]
Thanks. I closed the issue but I opened another issue in Github about
something closer to what I want to do substantively: I cannot access "data
objects" from the R package "RecordLinkage" with Rcall.

Anders

**Comment by aalexandersson** [comment]
When I run the R code

> R vanilla: source("temp.r")
> in a Stata do-file the R console generates an error message. But the
> console disappears before I can see what the error message is. I find
> errors in R vanilla difficult to debug. How can I read any R error messages
> from Rcall vanilla?

This is the code of temp.r:

library(RecordLinkage)  # load the package
rpatient1 <- st.data(patient1.dta)  # load Stata dataset in R
rbwhs1 <- st.data(bwhs1.dta)
rpairs <-
compare.linkage(rbwhs1,rpatient1,blockfld=c("ssn"),strcmp=4:7,exclude=c("pid","fname","lname"))
rpairs\$pairs[c(1:5), ]  # list pairs 1-5
rpairs <- emWeights(rpairs)  # calculate EM weights
summary(rpairs)  # show the weights
tail(getPairs(rpairs, 50, 0))  # list obs for classification
result <- emClassify(rpairs, 50, 40);  # classification
summary(result);                       # classification result
tmp <- getPairs(rpairs, 120, 40, single.rows=TRUE);  # extract L and P
load.data(tmp)  # load R data frame in Stata

The above R code works if I instead run Rcall interactively:

R: library(RecordLinkage)  # load the package
R: rpatient1 <- st.data(patient1.dta)  # load Stata dataset in R
etc.

But interactive use is too slow. Roger Newson's rsource() command runs in a
bout 3 minutes whereas R interactively takes about 45 minutes.

Anders

**Comment by haghish** [comment]
Anders please post your questions on Statalist. You will get benefit from many opinions and suggestions. This thread is for a very particular bug. I also check the Stata list everyday...

http://www.statalist.org/forums/

**Comment by aalexandersson** [comment]
Thanks. Done.
