### ISSUE TITLE
Microsoft R Open

### ISSUE THREAD

**Issue by econwang** [haghish/rcall#6]
I just try this cool tool, and find that it can not setpath if the routine does not find the R executable itself, this is mainly due to the error in Rcall.ado, where 
```
	// -------------------------------------------------------------------------
	// Search R path, if not specified
	// ===========================================
	capture prog drop Rpath
	capture Rpath
	
	tokenize `"`macval(0)'"'
	
	if `"`macval(1)'"' != "setpath" | `"`macval(1)'"' != "setpath:" {
```
the logic operator `|` should be fixed as `&`. By changing this, I can set the executable R to the microsoft r open.

Another issue is that, it seems Rcall will generate the R workspace and stataoutput file in current working dir, where the default in windows is something like `C:\Program Files (x86)\Stata14`, this dir is not writable by users by default, so it is necessary to set the working dir by users. My suggestion is that the Rcall routine can use a specific working dir for R workspace and stataoutput file, which makes the Rcall "Seamless"

**Comment by haghish** [comment]
I accepted your suggested correction. thanks for that. I am thinking if it is a good idea to create a directory and let Rcall only use that. However, I don't think that is a very good idea (although, very easy to do). Using the working directory provides many advantages and also, to me, it seems the natural work flow. 

Windows users always should watch out whether they have the rights to write and remove files in their current directory. perhaps an automated "warning" would be a better solution. You could write a "command"  that tests whether the user has the rights to write or remove a file in his current working directory and then use that command to return a proper error message...
