### ISSUE TITLE
Installing rcall

### ISSUE THREAD

**Issue by nksingh62** [haghish/rcall#8]
(1) At time of Installing *rcall* from github through command `github install haghish/rcall` at Stata,
message **unknown function ustrlower() r(133);** popup
Same message comes at time of installing *markdoc* from github. *markdoc has been successfully installed through `ssc install` command at my computer

(2) After installing *rcall* through `ssc install' command, getting message **unable to change to \bin
r(170);** at time of running R command from Stata. I am working on R 3.3.3 and its path is defined in windows 7 (sp1 32 bit) environment. I have installed readstata13 pkg at R.

**Comment by nksingh62** [comment]
Problem of installing *rcall* from *ssc* has been solved after assigning fixed value for path of R (as in my computer) to local macro  **newest_R**.
Problem of installing *rcall* from github is probably occurs due to unavailability of string functions related to unicode text in Stata 13.

**Comment by haghish** [comment]
`rcall` has not been updated on SSC for a year, and will not ever get updated there again. The only place you can download the latest version of the package is this repository. Stata 13 has problem with accessing GitHub, which can be solved by downloading the package and installing it locally...
