### ISSUE TITLE
rcall setpath not working

### ISSUE THREAD

**Issue by kylebarron** [haghish/rcall#9]
Hello,

I'm on Ubuntu 16.04, and just downloaded the latest version of this package from Github, i.e.
```stata
github install haghish/rcall
rcall setpath "/usr/bin/R"
```
But rcall still expects to find the binary in `/usr/local/bin/R`:
```stata
. rcall: a <- 100
R was expected in:  /usr/local/bin/R rcall could not find R on your system
```

When I put a symlink to the R binary in `/usr/local/bin/`, it still didn't work:
```stata
. rcall: a <- 100
stata.output.R script file not found. reinstall the package
invalid syntax
r(198);
```
But the package seems to be correctly installed:
```stata
. github install haghish/rcall
checking rcall consistency and verifying not already installed...
installing into /home/kyle/ado/plus/...
installation complete.

Checking package dipendencies
installing rcall package dependencies:


. // See the rcall help file for dependency details
. 
end of do-file

. net install rcall, replace from("https://raw.githubusercontent.com/haghish/rcall/master/")
checking rcall consistency and verifying not already installed...
all files already exist and are up to date.
```

**Comment by kylebarron** [comment]
FYI I'm using Stata/SE 15

**Comment by haghish** [comment]
try:

     di "`c(sysdir_plus)'r/Rpath.ado"

navigate to the path and by opening the ado file, confirm that the path has been registered in an ado file. If that is the case, I will look for other explanations, but so far, it seems to me that `rcall` cannot remember the path for some reasons. 

If you would like to investigate further, you could have a look at **rcall.ado** from line 375. That's where the R path is defined. 

PS. I don't have Linux nor Stata 15 at the moment...

**Comment by kylebarron** [comment]
This seems like a great package but you have a few issues.

Your biggest issue here is inconsistent capitalization. Inconsistent capitalization can slide for Windows or Mac, since they use case insensitive file systems. The file `R.ado` is the same as `r.ado` for those two OSes, but not for Linux. `R.ado` and `r.ado` are different files. 

The initial issue I hit above is that line [884](https://github.com/haghish/rcall/blob/master/rcall.ado#L884) of rcall.ado is looking for `stata.output.R`, and the package provides `stata.output.r`. On Linux those are different files and Stata doesn't know what to do. 

It seems like `net install` changes file names to lower case. On Linux, doing `net install rcall, from("https://raw.githubusercontent.com/haghish/rcall/master/")`, puts `r.ado` in my _plus_ directory, even though the repo has `R.ado`. 

Because of how that works (and since I see `github install` just uses `net install` underneath), the only options for Linux users are to manually download the files with the correct case into the _plus_ directory, or for you to rename all your files to lower case.

If I can get this to work I'd add R support to the Stata [syntax highlighting](https://atom.io/packages/language-stata) I wrote for Atom and Visual Studio Code.

Also, your documentation is outdated and doesn't work. It seems like the only package documentation is on your website, and that hasn't changed the `Rcall` vs `rcall` capitalization. For example, your site still says to use 
```
net install Rcall, replace from("https://raw.githubusercontent.com/haghish/Rcall/master/")
```
and that doesn't work because each case of `Rcall` needs to be `rcall`.

**Comment by haghish** [comment]
Thanks for the detailed explanation

- I've been very busy with new projects and maintaining the previous work is becoming a job for itself... That's why the documentation is outdated. On GitHub though, even the documentation can be written collectively. And really that's the only way to keep these stuff alive. So if you can push your suggestions to fix the package for linux, I'll gladly accept them. 

- did you manage to solve the problem with the manual R path definition?

**Comment by kylebarron** [comment]
I solved the first step, but beyond that I faced more issues and it wasn't worth it for me to try to debug everything.
